import sons from './sons'
import gallery from './gallery'
import contenu from './contenu'
import collaborateur from './collaborateur'
import video from './video'
import test from './textImage'
import about from './about'
import marketing from './marketing'
import titreText from './titreText'
import policy from './policy'
import titleTrad from './titleTrad'
import textTrad from './textTrad'
import news from './news'

export const schemaTypes = [news,textTrad,titleTrad,titreText,policy,marketing,test,about,sons, gallery, contenu, collaborateur, video]
