export default{
    name:'titleTrad',
    type:'object',
    title:'Traduction_Titre',
    fields:[
        {
            name:'fr',
            type:'string',
            title:'Francais'
        },
        {
            name:'de',
            type:'string',
            title:'Allemand'
        },
        {
            name:'en',
            type:'string',
            title:'Anglais'
        }
    ]
}